import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DNX COIN",
  description: "Generated by DanyxMeyer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🔁 Video Background */}
        <video
          id="background-video"
          autoPlay
          muted
          loop
          playsInline
          preload="auto"
          className="absolute inset-0 w-full h-full object-cover z-0"
        >
          {/* Updated video path */}
          <source
            src="/Videos/imagen-bh-dnx.mp4 07-58-50-160.mp4"
            type="video/mp4"
          />
          Your browser does not support the video tag.
        </video>
        {/* Render children (main content of your site) */}
        {children}
      </body>
    </html>
  );
}
